name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm install -g yarn

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install JS dependencies
        run: yarn
#      - run: yarn lint:sol
      - run: yarn coverage
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: true

